name: build
run-name: ${{ github.actor }}
on: 
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: npm install
      - run: npm run build